CREATE TABLE IF NOT EXISTS `teacher` (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY(`id`)
) ENGINE = MyISAM CHARSET = utf8;


CREATE TABLE IF NOT EXISTS `cls` (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    teacher_id INT UNSIGNED,
    PRIMARY KEY(`id`)
) ENGINE = MyISAM CHARSET = utf8;


CREATE TABLE IF NOT EXISTS `student` (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    cls_id INT UNSIGNED,
    PRIMARY KEY(`id`)
) ENGINE = MyISAM CHARSET = utf8;
